// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzsujqjcshlsujofkkqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56c3VqcWpjc2hsc3Vqb2Zra3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDAxNTgsImV4cCI6MjA2MjExNjE1OH0.7n9w47RpWHo8Nv0jcWPBdSeO9fydObg3hxHWgoLYY_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);